### ISSUE TITLE
[FEAT] Battle & 닉네임 변경 서버 통신 구현

### ISSUE THREAD

**Issue by kkk5474096** [zaranaramorimori/HACKER-ANDROID#55]
# 📝 DESCRIPTION
### Battle 서버 통신 구현

# ☑️ TODO
- [ ] Battle Season 서버 통신 구현
- [ ] Battle Rank 서버 통신 구현
- [ ] Battle Attack 서버 통신 구현
- [ ] 닉네임 변경 서버 통신 구현

**Comment by devkwonsehoon** [comment]
LGTM
